"""Onboarding domain schemas."""

from app.shared.domain import (
    ApiResponseBase,
    ApiResponsePaginated,
    ApiResponseSingle,
    PaginationResponse,
)
from app.microservices.onboarding.domain.onboarding_dto import (
    AddressDTO,
    CheckEmailResponseDTO,
    DocumentFileDTO,
    DocumentResponseDTO,
    DocumentUploadDTO,
    EDocumentSide,
    EOnboardingStatus,
    EOnboardingStep,
    EOtpChannel,
    EVerificationStatus,
    EWaitlistStatus,
    InviteResponseDTO,
    LeadResponseDTO,
    LegacyCurpBody,
    LegacyDireccionBody,
    LegacyRegistroBody,
    OnboardingResponseDTO,
    OnboardingStartDTO,
    OnboardingStartResponseDTO,
    OtpSendDTO,
    OtpSentResponseDTO,
    OtpVerifyDTO,
    PasswordSetupDTO,
    PersonalInfoDTO,
    RegisterLeadDTO,
)

__all__ = [
    "ApiResponseBase",
    "ApiResponsePaginated",
    "ApiResponseSingle",
    "PaginationResponse",
    "AddressDTO",
    "CheckEmailResponseDTO",
    "DocumentFileDTO",
    "DocumentResponseDTO",
    "DocumentUploadDTO",
    "EDocumentSide",
    "EOnboardingStatus",
    "EOnboardingStep",
    "EOtpChannel",
    "EVerificationStatus",
    "EWaitlistStatus",
    "InviteResponseDTO",
    "LeadResponseDTO",
    "LegacyCurpBody",
    "LegacyDireccionBody",
    "LegacyRegistroBody",
    "OnboardingResponseDTO",
    "OnboardingStartDTO",
    "OnboardingStartResponseDTO",
    "OtpSendDTO",
    "OtpSentResponseDTO",
    "OtpVerifyDTO",
    "PasswordSetupDTO",
    "PersonalInfoDTO",
    "RegisterLeadDTO",
]
