"""Core domain schemas."""

from app.shared.domain import (
    ApiResponseBase,
    ApiResponsePaginated,
    ApiResponseSingle,
    CountResponse,
    MessageResponse,
    PaginationResponse,
)
from app.microservices.core.domain.core_dto import (
    AddressResponseDTO,
    CreateAddressDTO,
    CreateEmailDTO,
    CreateEmergencyContactDTO,
    CreateIdentifierDTO,
    CreatePersonDTO,
    CreatePhoneDTO,
    EmailResponseDTO,
    EmergencyContactResponseDTO,
    IdentifierResponseDTO,
    PersonExistsResponseDTO,
    PersonResponseDTO,
    PhoneResponseDTO,
    UpdateAddressDTO,
    UpdateEmailDTO,
    UpdateEmergencyContactDTO,
    UpdateIdentifierDTO,
    UpdatePersonDTO,
    UpdatePersonStatusDTO,
    UpdatePhoneDTO,
)

__all__ = [
    "ApiResponseBase",
    "ApiResponsePaginated",
    "ApiResponseSingle",
    "CountResponse",
    "MessageResponse",
    "PaginationResponse",
    "AddressResponseDTO",
    "CreateAddressDTO",
    "CreateEmailDTO",
    "CreateEmergencyContactDTO",
    "CreateIdentifierDTO",
    "CreatePersonDTO",
    "CreatePhoneDTO",
    "EmailResponseDTO",
    "EmergencyContactResponseDTO",
    "IdentifierResponseDTO",
    "PersonExistsResponseDTO",
    "PersonResponseDTO",
    "PhoneResponseDTO",
    "UpdateAddressDTO",
    "UpdateEmailDTO",
    "UpdateEmergencyContactDTO",
    "UpdateIdentifierDTO",
    "UpdatePersonDTO",
    "UpdatePersonStatusDTO",
    "UpdatePhoneDTO",
]
